<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.QuickGrid" Version="9.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ShortBox.ServiceDefaults\ShortBox.ServiceDefaults.csproj" />
    <ProjectReference Include="..\ShortBox.Azure\ShortBox.Azure.csproj" />
  </ItemGroup>

</Project>
