@ShortBox.Api_HostAddress = http://jweeks-spector:5000
@SeriesName = "Fantastic Four"

###

GET {{ShortBox.Api_HostAddress}}/series/{{SeriesName}}

###
GET {{ShortBox.Api_HostAddress}}/series/{{SeriesName}}/archive

