<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>92587946-8485-4fdc-a8d7-328f45250f8d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.24.0" />
    <PackageReference Include="Microsoft.Extensions.Azure" Version="1.11.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ShortBox.Google\ShortBox.Google.csproj" />
    <ProjectReference Include="..\ShortBox.Azure.Services\ShortBox.Azure.Services.csproj" />
    <ProjectReference Include="..\ShortBox.Azure\ShortBox.Azure.csproj" />
  </ItemGroup>

</Project>
